### ISSUE TITLE
Clicked disable now it doesnt work

### ISSUE THREAD

**Issue by TalkingBenStan** [vdsk/rbxstudiopatcher#1]
It worked but I clicked disable internal on top and it wont load internal anymore.

**Comment by vdsk** [comment]
> It worked but I clicked disable internal on top and it wont load internal anymore.

go into this folder
%homepath%\AppData\Local\Roblox
and delete "GlobalSettings_13.xml"

**Comment by TalkingBenStan** [comment]
worked thanks

**Comment by TalkingBenStan** [comment]
can u list some of the things you can do with the internal build?

**Comment by TalkingBenStan** [comment]
Also is there an internal version of the regular roblox client? If so is there anyway to enable it.
